services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3500:3500"
    volumes:
      - pub-docs:/app/pub-docs
      - pub-local:/app/pub-local

volumes:
  pub-docs:
  pub-local:
