services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3500:3500"
    volumes:
      - pub-docs:/app/pub-docs
      - pub-local:/app/pub-local
    expose:
      - "3500"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-certs:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        sleep 12h & wait $${!};
      done"

volumes:
  pub-docs:
  pub-local:
  certbot-certs:
  certbot-www:
